site_name: hydrolib-demotool documentation
theme:
  name: material
  language: en
  custom_dir: docs/overrides
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
plugins:
  - search
  - mkdocs-jupyter
  - autorefs
  - macros:
      module_name: docs/include/mkdocs-macros/main
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_toc_entry: false
            show_source: true
            show_signature_annotations: true
            heading_level: 3
            show_category_heading: false
            group_by_category: false
          selection:
            inherited_members: false

      custom_templates: templates
      watch:
        - hydrolib_demotool
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
repo_url: https://github.com/Deltares/hydrolib-demotool
repo_name: deltares/hydrolib-demotool
edit_uri: edit/main/docs/
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Deltares/hydrolib-demotool
      name: Source code
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/Deltares/hydrolib
      name: Chat with us on Gitter
copyright: Copyright &copy; 2022 Deltares
extra_css:
  - stylesheets/extra.css

nav:
  - Home: "index.md"
  - Changelog: "changelog.md"
